### ISSUE TITLE
New Overrides

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#947]
The new overrides should fix many of the issues of the old overrides and allow us to use the override system elsewhere easily.

- [x] ~~Add separate override validation (and unit tests)~~ #671 
- [x] ~~Add separate new overrides (and unit tests) - migrates one TF product~~ #973
- [x] ~~Migrate from old overrides to new overrides~~
  - [x] ~~Terraform~~ #1089
  - [x] ~~Ansible~~ #1153 
  - [x] ~~Inspec~~ #1153 
- [x] ~~Delete old overrides~~ #1222 
- [x] ~~Place overrides into better namespace~~ #1242
